export enum ArgProvincesEnum {
  CABA = "Ciudad Autónoma de Buenos Aires",
  BUE = "Buenos Aires",
  CAT = "Catamarca",
  CHA = "Chaco",
  CHU = "Chubut",
  COR = "Córdoba",
  CORR = "Corrientes",
  ER = "Entre Ríos",
  FOR = "Formosa",
  JUJ = "Jujuy",
  LP = "La Pampa",
  LR = "La Rioja",
  MEN = "Mendoza",
  MIS = "Misiones",
  NEU = "Neuquén",
  RN = "Río Negro",
  SAL = "Salta",
  SJ = "San Juan",
  SL = "San Luis",
  SC = "Santa Cruz",
  SF = "Santa Fe",
  SE = "Santiago del Estero",
  TF = "Tierra del Fuego",
  TUC = "Tucumán",
}
