export enum CurrencyEnum {
  USD = 'USD', // United States Dollar
  EUR = 'EUR', // Euro
  GBP = 'GBP', // British Pound Sterling
  JPY = 'JPY', // Japanese Yen
  CNY = 'CNY', // Chinese Yuan
  INR = 'INR', // Indian Rupee
  BRL = 'BRL', // Brazilian Real
  CAD = 'CAD', // Canadian Dollar
  AUD = 'AUD', // Australian Dollar
  CHF = 'CHF', // Swiss Franc
  MXN = 'MXN', // Mexican Peso
  ZAR = 'ZAR', // South African Rand
  RUB = 'RUB', // Russian Ruble
  SGD = 'SGD', // Singapore Dollar
  HKD = 'HKD', // Hong Kong Dollar
  NOK = 'NOK', // Norwegian Krone
  SEK = 'SEK', // Swedish Krona
  DKK = 'DKK', // Danish Krone
  TRY = 'TRY', // Turkish Lira
  KRW = 'KRW', // South Korean Won
  SAR = 'SAR', // Saudi Riyal
  NZD = 'NZD', // New Zealand Dollar
  THB = 'THB', // Thai Baht
  AED = 'AED', // United Arab Emirates Dirham
  PLN = 'PLN', // Polish Zloty
  ILS = 'ILS', // Israeli New Shekel
  CLP = 'CLP', // Chilean Peso
  PHP = 'PHP', // Philippine Peso
  COP = 'COP', // Colombian Peso
  MYR = 'MYR', // Malaysian Ringgit
  RON = 'RON', // Romanian Leu
  VND = 'VND', // Vietnamese Dong
  ARS = 'ARS', // Argentine Peso
  HUF = 'HUF', // Hungarian Forint
  CZK = 'CZK', // Czech Koruna
  IDR = 'IDR', // Indonesian Rupiah
  EGP = 'EGP', // Egyptian Pound
  NGN = 'NGN', // Nigerian Naira
  PKR = 'PKR', // Pakistani Rupee
  UAH = 'UAH', // Ukrainian Hryvnia
  MAD = 'MAD', // Moroccan Dirham
  BGN = 'BGN', // Bulgarian Lev
  LKR = 'LKR', // Sri Lankan Rupee
  BDT = 'BDT', // Bangladeshi Taka
}
